name: test

on:
  workflow_dispatch:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
    env:
      BSC_RPC_URL: https://bsc-dataseed.binance.org
      EVMOS_RPC_URL: https://evmos-mainnet.public.blastapi.io
      KEEPER_CALLER_ADDRESS: 0x9222AE32f5eEEC408DD413f081D91A4105f3b138
      AUTHORITY_ADDRESS: 0x89E3E7b8EF087A1DE0D57d52c9249c60780FAD8d
      FEES_CONTROLLER_ADDRESS: 0xcD99513ed76143c5E87BCf91BAff8313d94856F5
      KEEPER_ADDRESS: 0x1F61D2c8216791D8b946e5338452115FA062F749

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Get changed files in the vaults-config folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            vaults-config/**

      - name: Test deployment of new strats
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for vault_config in "${{ steps.changed-files-specific.outputs.all_changed_files }}"; do
            STRAT_CONFIG_FILE=$vault_config forge test --match-path test/prod/deploy-strat.t.sol
          done

