name: test

on:
  workflow_dispatch:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Get changed files in the vaults-config folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            vaults-config/**

      - name: Test deployment of new strats
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for vault_config in "${{ steps.changed-files-specific.outputs.all_changed_files }}"; do
            STRAT_CONFIG_FILE=$vault_config forge test --match-path test/prod/deploy-strat.t.sol
          done

